# Generated by Django 5.0.4 on 2024-05-25 06:53

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="dob",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_pictire",
            field=models.ImageField(
                default="students/students.png",
                null=True,
                upload_to=mainapp.models.unique_img_name,
            ),
        ),
    ]
